//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonView
    {
        public string MaHD { get; set; }
        public string TenHH { get; set; }
        public int QtyHD { get; set; }
        public double DonGiaHH { get; set; }
        public double ThanhTien { get; set; }
        public Nullable<int> SalesDc { get; set; }
        public System.DateTime NgayGD { get; set; }
        public string TenNV { get; set; }
        public string TenKH { get; set; }
    }
}
