//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RetroCityPBL3Entities : DbContext
    {
        public RetroCityPBL3Entities()
            : base("name=RetroCityPBL3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<View_BHCuoiNgay> View_BHCuoiNgay { get; set; }
        public virtual DbSet<View_BHHangHoa> View_BHHangHoa { get; set; }
        public virtual DbSet<View_HHCuoiNgay> View_HHCuoiNgay { get; set; }
        public virtual DbSet<View_LNBanHang> View_LNBanHang { get; set; }
        public virtual DbSet<View_LNHangHoa> View_LNHangHoa { get; set; }
        public virtual DbSet<View_NVBanHang> View_NVBanHang { get; set; }
    }
}
