//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_BHHangHoa
    {
        public string MaHH { get; set; }
        public string TenHH { get; set; }
        public int SL_Ban { get; set; }
        public Nullable<double> DoanhThu { get; set; }
        public Nullable<System.DateTime> NgayGD { get; set; }
    }
}
