//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_BHCuoiNgay
    {
        public string MaHD { get; set; }
        public string TenKH { get; set; }
        public string TenNV { get; set; }
        public Nullable<System.DateTime> NgayGD { get; set; }
        public string ThoiGian { get; set; }
        public Nullable<int> SL { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<double> GiamGia { get; set; }
        public Nullable<double> DoanhThu { get; set; }
    }
}
