//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_LNBanHang
    {
        public System.DateTime NgayGD { get; set; }
        public Nullable<double> TongTienHang { get; set; }
        public Nullable<double> GiamGia { get; set; }
        public Nullable<double> DoanhThu { get; set; }
        public Nullable<double> TongGiaVon { get; set; }
        public Nullable<double> LoiNhuanGop { get; set; }
    }
}
